"""Extra Decoy Brief packs for Fibbage-starved WAPS chapters.

Original study lines. Facts follow AFH 1 (15 February 2025) as already
taught in this bank. explain is study copy. source is only the locator.
"""

DECOY_EXTRA = [
    {
        "ch": 17, "sec": "17A", "para": "17A", "title": "All-Hazards",
        "page": 321, "ranks": "both", "diff": 2,
        "stem": "Which statement matches the emergency-management approach in the handbook?",
        "truth": "One preparedness system covers natural, technological, and adversary hazards",
        "decoys": [
            "Only enemy attacks belong in the emergency plan",
            "Weather emergencies are left to morale programs",
            "Each hazard type must have its own unconnected command chain",
        ],
        "explain": "All-hazards means the installation prepares once for the dangers it can actually face. A separate system for every label, or a plan that ignores weather and accidents, leaves holes.",
        "source": "AFH 1 (2025) section 17A — USAF Emergency Management.",
    },
    {
        "ch": 17, "sec": "17B", "para": "17B", "title": "Disasters, Attacks, and Hazards",
        "page": 323, "ranks": "both", "diff": 2,
        "stem": "A chemical, biological, radiological, or nuclear attack belongs with which handbook grouping?",
        "truth": "Disasters, attacks, and hazards",
        "decoys": [
            "Dress and appearance standards",
            "Leave and liberty rules",
            "Promotion-test scoring",
        ],
        "explain": "CBRN attacks sit in the same hazard picture as natural disasters and major accidents. Uniforms, leave, and testing are other chapters.",
        "source": "AFH 1 (2025) section 17B — Disasters, Attacks, and Hazards.",
    },
    {
        "ch": 17, "sec": "17C", "para": "17C", "title": "Preparedness and Protection",
        "page": 327, "ranks": "both", "diff": 2,
        "stem": "Preparedness in the emergency-management chapter is mainly about what?",
        "truth": "Plans, training, and equipment so the response is not invented during the crisis",
        "decoys": [
            "Writing the after-action story before the event",
            "Waiting for the first alarm to assign duties",
            "Replacing the chain of command with a volunteer list",
        ],
        "explain": "Preparedness is the work done before the alarm. Assigning duties after the alarm, or swapping the chain for volunteers, is the failure this section is written to prevent.",
        "source": "AFH 1 (2025) section 17C — Preparedness and Protection.",
    },
    {
        "ch": 17, "sec": "17D", "para": "17D", "title": "Response and Recovery",
        "page": 331, "ranks": "both", "diff": 2,
        "stem": "After the immediate danger is contained, recovery is aimed at what?",
        "truth": "Restoring essential mission capability, not only cleaning up visible damage",
        "decoys": [
            "Declaring the emergency over when the parking lot is swept",
            "Skipping the mission and focusing on a press release",
            "Restarting ordinary leave before the mission is back",
        ],
        "explain": "A clean lot can hide a dead mission. Recovery means essential work is running again, not that the visible mess is gone.",
        "source": "AFH 1 (2025) section 17D — Response and Recovery.",
    },
    {
        "ch": 17, "sec": "17E", "para": "17E", "title": "Mishap Prevention",
        "page": 334, "ranks": "both", "diff": 2,
        "stem": "Mishap prevention asks Airmen to deal with a hazard when?",
        "truth": "Before people and equipment are hurt",
        "decoys": [
            "Only after a reportable injury",
            "Only when an inspector is already on the schedule",
            "After the decoration package is written",
        ],
        "explain": "Prevention removes or controls the hazard early. Waiting for the injury, the inspector, or an award write-up gives the hazard time to win.",
        "source": "AFH 1 (2025) section 17E — Mishap Prevention.",
    },
    {
        "ch": 17, "sec": "17F", "para": "17F", "title": "Risk Management",
        "page": 336, "ranks": "both", "diff": 2,
        "stem": "After controls are in place, the risk-management cycle still requires what?",
        "truth": "Supervise the controls and evaluate whether they work",
        "decoys": [
            "File the worksheet and stop looking",
            "Assume a signed form means the risk is gone",
            "Hand the residual risk to the newest Airman with no follow-up",
        ],
        "explain": "The last step keeps the control honest. A worksheet nobody checks is not a finished cycle, and a signature does not retire the hazard by itself.",
        "source": "AFH 1 (2025) section 17F — Risk Management.",
    },
    {
        "ch": 20, "sec": "20A", "para": "20A", "title": "Air Force Inspection System",
        "page": 377, "ranks": "both", "diff": 2,
        "stem": "The Air Force Inspection System is built to assess what?",
        "truth": "Readiness, compliance, and continuous improvement",
        "decoys": [
            "Who can write the best slogan",
            "How fast a unit can hide a defect",
            "Which flight has the newest furniture",
        ],
        "explain": "Inspections look at whether the unit can do the mission, follow the standard, and get better. Hiding a defect is a failure of the system, not a technique inside it.",
        "source": "AFH 1 (2025) section 20A — Air Force Inspection System.",
    },
    {
        "ch": 20, "sec": "20A", "para": "20A", "title": "Self-Assessment",
        "page": 377, "ranks": "both", "diff": 2,
        "stem": "A useful self-assessment finds a defect when?",
        "truth": "While the unit can still fix it",
        "decoys": [
            "After the inspector has left and the score is final",
            "Only if the defect makes the unit look busy",
            "When a rumor has already replaced the standard",
        ],
        "explain": "Looking at your own unit is useful when there is still time to repair the problem. Waiting for a final score wastes the tool.",
        "source": "AFH 1 (2025) section 20A — Self-Assessment.",
    },
    {
        "ch": 20, "sec": "20B", "para": "20B", "title": "Individual Accountability",
        "page": 382, "ranks": "both", "diff": 2,
        "stem": "Individual accountability in this chapter attaches to what?",
        "truth": "The member's own conduct and the duties they were trusted with",
        "decoys": [
            "Only the person who wrote the policy",
            "Only the commander, so Airmen can skip the standard",
            "Only whatever the group chat agrees to",
        ],
        "explain": "Accountability stays personal. A policy author, a commander, or a chat does not carry the duty that was trusted to the member.",
        "source": "AFH 1 (2025) section 20B — Individual Accountability.",
    },
    {
        "ch": 20, "sec": "20C", "para": "20C", "title": "Unprofessional Relationships",
        "page": 385, "ranks": "both", "diff": 2,
        "stem": "Which relationship does the handbook treat as unprofessional?",
        "truth": "One that compromises, or reasonably appears to compromise, the chain of command or good order",
        "decoys": [
            "Any friendship between people in the same unit",
            "A mentoring talk that stays inside the duty",
            "Two Airmen who carpool and keep the same standard",
        ],
        "explain": "The test is the chain and good order, including how the relationship looks. Ordinary professional contact is not the problem the section names.",
        "source": "AFH 1 (2025) section 20C — Unprofessional Relationships.",
    },
    {
        "ch": 20, "sec": "20C", "para": "20C", "title": "Favoritism",
        "page": 385, "ranks": "both", "diff": 2,
        "stem": "Favoritism in the standards chapter means what?",
        "truth": "Preferential treatment or misuse of position",
        "decoys": [
            "Giving every Airman the same feedback",
            "Enforcing one standard on every shift",
            "Documenting a real performance difference",
        ],
        "explain": "Favoritism is uneven treatment that comes from the relationship or the position. Equal enforcement, and a real performance note, are the opposite of that misuse.",
        "source": "AFH 1 (2025) section 20C — Favoritism.",
    },
    {
        "ch": 20, "sec": "20D", "para": "20D", "title": "Addressing Misconduct",
        "page": 390, "ranks": "both", "diff": 2,
        "stem": "The first move when correcting misconduct should be what?",
        "truth": "Correct the behavior at the lowest effective level, and escalate if it continues",
        "decoys": [
            "Start with the heaviest punishment every time",
            "Ignore it until a stranger complains",
            "Move the Airman and leave the behavior untouched",
        ],
        "explain": "Lowest effective level still means the behavior changes. Doing nothing, or jumping to the ceiling with no reason, both miss the point of the tool.",
        "source": "AFH 1 (2025) section 20D — Addressing Misconduct.",
    },
    {
        "ch": 22, "sec": "22A", "para": "22A", "title": "USAF Fitness",
        "page": 414, "ranks": "both", "diff": 1,
        "stem": "The handbook's purpose for fitness is what?",
        "truth": "A force that can do the mission",
        "decoys": [
            "A cosmetic contest",
            "A number collected for its own sake",
            "A way to sort people for decorations",
        ],
        "explain": "Fitness is readiness for the mission. Appearance, a lonely score, and award sorting are not the purpose the chapter gives.",
        "source": "AFH 1 (2025) section 22A — USAF Fitness.",
    },
    {
        "ch": 22, "sec": "22B", "para": "22B", "title": "Fitness Assessment",
        "page": 418, "ranks": "both", "diff": 2,
        "stem": "Why does this study bank leave specific fitness numbers out of the items?",
        "truth": "Components and scoring change, and the current instruction controls",
        "decoys": [
            "Fitness scores are classified",
            "The Air Force no longer measures fitness",
            "Any unit may invent its own scoring",
        ],
        "explain": "The durable lesson is to follow the current fitness instruction. A memorized number can go stale the day the instruction changes, and units do not get to freelance the scale.",
        "source": "AFH 1 (2025) section 22B — Fitness Assessment.",
    },
    {
        "ch": 22, "sec": "22C", "para": "22C", "title": "Nutrition",
        "page": 424, "ranks": "both", "diff": 2,
        "stem": "Nutrition is in the fitness chapter because readiness includes what?",
        "truth": "Fuel and recovery, not exercise alone",
        "decoys": [
            "Skipping meals to chase a weight goal",
            "Energy drinks as a substitute for sleep",
            "A diet that only matters the week of the test",
        ],
        "explain": "The body that has to do the mission needs fuel and recovery the whole time. A last-week trick, a skipped meal, or a drink in place of sleep is not the lesson.",
        "source": "AFH 1 (2025) section 22C — Nutrition.",
    },
    {
        "ch": 22, "sec": "22D", "para": "22D", "title": "Substance Abuse",
        "page": 429, "ranks": "both", "diff": 2,
        "stem": "Illegal drug use is treated as incompatible with service because it breaks what?",
        "truth": "Readiness and the trust the team has to place in the member",
        "decoys": [
            "Only the uniform regulation",
            "Nothing, if the member is off duty",
            "Only the member's social media following",
        ],
        "explain": "A force that cannot trust the person next to them is not ready. Off-duty timing and online excuses do not put that trust back.",
        "source": "AFH 1 (2025) section 22D — Substance Abuse.",
    },
    {
        "ch": 22, "sec": "22D", "para": "22D", "title": "Alcohol",
        "page": 429, "ranks": "both", "diff": 2,
        "stem": "Misuse of alcohol matters in this chapter because it can damage what?",
        "truth": "Health, judgment, and the people who have to count on the member",
        "decoys": [
            "Only the member's private weekend",
            "Nothing, if the shift has not started",
            "Only a line on a decoration citation",
        ],
        "explain": "The people who depend on the member inherit the bad judgment. The section does not treat that as a private hobby with no duty attached.",
        "source": "AFH 1 (2025) section 22D — Alcohol.",
    },
    {
        "ch": 22, "sec": "22E", "para": "22E", "title": "Readiness State of Mind",
        "page": 434, "ranks": "both", "diff": 2,
        "stem": "A readiness state of mind means the Airman does what?",
        "truth": "Stays mentally prepared to deploy and to do the job under stress",
        "decoys": [
            "Waits to think about deployment until the night before",
            "Treats asking for help as proof they should be removed",
            "Measures readiness only by how busy they look",
        ],
        "explain": "Mental readiness is being able to go and to work under stress. Last-minute panic, punishing help-seeking, and looking busy are not that state of mind.",
        "source": "AFH 1 (2025) section 22E — Readiness State of Mind.",
    },
]
