"""Decoy Brief rows converted from this project's retired Fibbage prompts.

Truths and decoys are original to this project. explain is study copy.
source is only the handbook locator. These rows are not loaded from the parked Fibbage files.
"""

DECOY = [{'ch': 1,
  'sec': '1A',
  'para': '1.1',
  'title': 'Professionalism',
  'page': 18,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? AFH 1 says the root of professionalism is ____.',
  'truth': 'Respect',
  'decoys': ['Rank', 'Fitness', 'Secrecy'],
  'explain': 'Paragraph 1.1 names respect as the root. Rank and fitness matter elsewhere and are not the '
             'root.',
  'source': 'AFH 1 (2025) para 1.1 — Professionalism.'},
 {'ch': 1,
  'sec': '1B',
  'para': '1.2',
  'title': 'Profession of Arms',
  'page': 19,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The profession of arms is distinguished by expertise in '
          'the justified application of ____.',
  'truth': 'lethal military force',
  'decoys': ['federal budget authority', 'civilian employment law', 'installation morale funds'],
  'explain': 'Paragraph 1.2 names lethal military force as the expertise that sets the profession apart. '
             'Budget, employment law, and morale funds are not that distinction.',
  'source': 'AFH 1 (2025) para 1.2 — Profession of Arms.'},
 {'ch': 1,
  'sec': '1B',
  'para': '1.2',
  'title': 'Profession of Arms',
  'page': 19,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? The profession of arms is distinguished by expertise in '
          'the justified use of ____.',
  'truth': 'Lethal military force',
  'decoys': ['Installation Wi-Fi', 'Performance reports', 'Drill only'],
  'explain': 'Paragraph 1.2 names lethal force applied with justification. Admin skills are not the '
             'distinction.',
  'source': 'AFH 1 (2025) para 1.2 — Profession of Arms.'},
 {'ch': 1,
  'sec': '1C',
  'para': '1.3',
  'title': 'Core Values',
  'page': 20,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The Air Force core values are Integrity First, Service '
          'Before Self, and ____.',
  'truth': 'Excellence In All We Do',
  'decoys': ['Excellence In Most Things', 'Courage Under Fire', 'Duty Honor Country'],
  'explain': 'Paragraph 1.3 names Excellence In All We Do as the third core value. The fakes swap in a '
             "softer slogan or another service's words.",
  'source': 'AFH 1 (2025) para 1.3 — Core Values.'},
 {'ch': 1,
  'sec': '1C',
  'para': '1.3',
  'title': 'Air Force Core Values',
  'page': 20,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The three Air Force core values are Integrity First, '
          'Service Before Self, and ____.',
  'truth': 'Excellence In All We Do',
  'decoys': ['Duty Honor Country', 'Honor Courage Commitment', 'Aim High Fly Fight Win'],
  'explain': 'Paragraph 1.3 names Excellence In All We Do as the third core value. The other phrases are '
             'mottos, not that value.',
  'source': 'AFH 1 (2025) para 1.3 — Air Force Core Values.'},
 {'ch': 1,
  'sec': '1C',
  'para': '1.3.1',
  'title': 'Integrity First',
  'page': 20,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? Integrity is doing the right thing all the time, whether '
          'everyone is watching or ____.',
  'truth': 'no one is watching',
  'decoys': ['a supervisor is in the room', 'the mission can spare it', 'the news would approve'],
  'explain': 'Paragraph 1.3.1 defines integrity as doing the right thing whether or not anyone is watching. '
             'The other endings make integrity depend on an audience.',
  'source': 'AFH 1 (2025) para 1.3.1 — Integrity First.'},
 {'ch': 1,
  'sec': '1C',
  'para': '1.3.1',
  'title': 'Integrity Virtues',
  'page': 20,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The virtues of Integrity First are honesty, courage, and '
          '____.',
  'truth': 'Accountability',
  'decoys': ['Loyalty', 'Teamwork', 'Discipline'],
  'explain': 'Accountability completes the Integrity First virtues. Loyalty belongs to Service Before Self, '
             'and teamwork and discipline belong to Excellence.',
  'source': 'AFH 1 (2025) para 1.3.1 — Integrity Virtues.'},
 {'ch': 1,
  'sec': '1C',
  'para': '1.3.2',
  'title': 'Service Before Self',
  'page': 20,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Loyalty runs to the nation first, Air Force values second, '
          'and finally to ____.',
  'truth': 'the people we serve with',
  'decoys': ['the next assignment', 'our own career', 'the nearest supervisor only'],
  'explain': 'Paragraph 1.3.2 places fellow Airmen third, after the nation and Air Force values. Career, '
             'assignment, and a supervisor-only loyalty reverse that order.',
  'source': 'AFH 1 (2025) para 1.3.2 — Service Before Self.'},
 {'ch': 1,
  'sec': '1C',
  'para': '1.3.2',
  'title': 'Service Virtues',
  'page': 20,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Service Before Self is practiced through duty, loyalty, '
          'and ____.',
  'truth': 'Respect',
  'decoys': ['Honesty', 'Mission', 'Speed'],
  'explain': 'Respect is the third virtue of Service Before Self. Honesty is an integrity virtue, and '
             'mission is an excellence virtue.',
  'source': 'AFH 1 (2025) para 1.3.2 — Service Virtues.'},
 {'ch': 1,
  'sec': '1C',
  'para': '1.5',
  'title': "Airman's Creed",
  'page': 18,
  'ranks': 'both',
  'diff': 2,
  'stem': "Which completion is the handbook line? General Moseley presented the Airman's Creed to the Air "
          'Force in ____.',
  'truth': '2007',
  'decoys': ['1947', '1991', '2014'],
  'explain': "Paragraph 1.5 dates the creed to 2007. 1947 is the Air Force's establishment, not the creed.",
  'source': "AFH 1 (2025) para 1.5 — Airman's Creed."},
 {'ch': 1,
  'sec': '1D',
  'para': '1.5',
  'title': "The Airman's Creed",
  'page': 23,
  'ranks': 'both',
  'diff': 2,
  'stem': "Which completion is the handbook line? The Airman's Creed says the mission is to ____.",
  'truth': 'Fly, Fight, and Win',
  'decoys': ['Serve, Support, and Sustain', 'Train, Organize, and Equip only', 'Deter, Dissuade, and Delay'],
  'explain': 'The creed in paragraph 1.5 states the mission as Fly, Fight, and Win. The other trios are not '
             "the creed's mission line.",
  'source': "AFH 1 (2025) para 1.5 — The Airman's Creed."},
 {'ch': 5,
  'sec': '5A',
  'para': '5.1',
  'title': 'Command Authority',
  'page': 89,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? For forces assigned to combatant commanders, command runs '
          'from the President through the Secretary of Defense to the ____.',
  'truth': 'combatant commanders',
  'decoys': ['service secretaries', 'Chairman as commander', 'wing first sergeants'],
  'explain': 'Paragraph 5.1 names combatant commanders for assigned forces. Service secretaries are the path '
             'for unassigned forces, and the Chairman does not command.',
  'source': 'AFH 1 (2025) para 5.1 — Command Authority.'},
 {'ch': 5,
  'sec': '5A',
  'para': '5.1',
  'title': 'Chain of Command',
  'page': 89,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? For forces under combatant commanders, the chain runs '
          'President, Secretary of Defense, then ____.',
  'truth': 'The combatant commanders',
  'decoys': ['The wing first sergeant', 'The service chief only', 'Congress directly'],
  'explain': 'Paragraph 5.1 places combatant commanders at the end of that operational chain.',
  'source': 'AFH 1 (2025) para 5.1 — Chain of Command.'},
 {'ch': 5,
  'sec': '5A',
  'para': '5.2',
  'title': 'Department of Defense',
  'page': 89,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The Department of Defense mission is to provide military '
          'forces to deter war and protect the ____.',
  'truth': 'security of our country',
  'decoys': ['pay of every civilian agency', 'state Guard in peacetime', 'promotion quotas of each service'],
  'explain': "Paragraph 5.2 states the mission as deterring war and protecting the country's security. Pay, "
             'peacetime state duty, and quotas are not that mission.',
  'source': 'AFH 1 (2025) para 5.2 — Department of Defense.'},
 {'ch': 5,
  'sec': '5C',
  'para': '5.7',
  'title': 'Unified Command Plan',
  'page': 95,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? The Unified Command Plan is reviewed and updated every '
          '____ years.',
  'truth': 'Two',
  'decoys': ['Five', 'Ten', 'One'],
  'explain': 'Paragraph 5.7 says the plan is updated every two years.',
  'source': 'AFH 1 (2025) para 5.7 — Unified Command Plan.'},
 {'ch': 5,
  'sec': '5C',
  'para': '5.8',
  'title': 'Combatant Commands',
  'page': 95,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? AFH 1 says there are currently ____ unified combatant '
          'commands.',
  'truth': '11',
  'decoys': ['7', '4', '50'],
  'explain': 'Paragraph 5.8 states the current number is 11. Four is only the functional commands named in '
             'that passage.',
  'source': 'AFH 1 (2025) para 5.8 — Combatant Commands.'},
 {'ch': 5,
  'sec': '5C',
  'para': '5.8',
  'title': 'Combatant Command Organization',
  'page': 95,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The handbook says there are currently ____ unified '
          'combatant commands.',
  'truth': '11',
  'decoys': ['6', '4', '9'],
  'explain': 'Paragraph 5.8 says there are currently 11. Six is the geographic count in that section, and '
             'four is the functional list named before Space Command is also described.',
  'source': 'AFH 1 (2025) para 5.8 — Combatant Command Organization.'},
 {'ch': 5,
  'sec': '5C',
  'para': '5.8',
  'title': 'Combatant Command Organization',
  'page': 95,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? United States Africa Command is at Kelley Barracks in '
          '____.',
  'truth': 'Stuttgart',
  'decoys': ['Tampa', 'Honolulu', 'Miami'],
  'explain': 'Paragraph 5.8 places Africa Command at Kelley Barracks, Stuttgart. Tampa is associated with '
             "MacDill's Florida commands, Honolulu with Indo-Pacific Command, and Miami with Southern "
             'Command.',
  'source': 'AFH 1 (2025) para 5.8 — Combatant Command Organization.'},
 {'ch': 5,
  'sec': '5E',
  'para': '5.15',
  'title': 'Air Staff A1',
  'page': 101,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? On the Air Staff, the A1 office symbol covers manpower, '
          'personnel, and ____.',
  'truth': 'Services',
  'decoys': ['Operations', 'Logistics', 'Nuclear integration'],
  'explain': 'Paragraph 5.15 assigns services to A1. Operations is A3 and logistics is A4.',
  'source': 'AFH 1 (2025) para 5.15 — Air Staff A1.'},
 {'ch': 5,
  'sec': '5E',
  'para': '5.15',
  'title': 'CSAF Term',
  'page': 101,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The Chief of Staff of the Air Force is appointed for ____ '
          'years.',
  'truth': 'Four',
  'decoys': ['Two', 'Six', 'Eight'],
  'explain': 'Paragraph 5.15 states a four-year appointment.',
  'source': 'AFH 1 (2025) para 5.15 — CSAF Term.'},
 {'ch': 5,
  'sec': '5E',
  'para': '5.16',
  'title': 'Subordinate Levels',
  'page': 101,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The basic unit and building block of the Air Force is the '
          '____.',
  'truth': 'squadron',
  'decoys': ['flight', 'group', 'element'],
  'explain': 'Paragraph 5.16 calls the squadron the basic unit. Flight, group, and element are other '
             'echelons.',
  'source': 'AFH 1 (2025) para 5.16 — Subordinate Levels.'},
 {'ch': 7,
  'sec': '7B',
  'para': '7.5',
  'title': 'ALS Gate',
  'page': 128,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? A Senior Airman must complete ____ before assuming Staff '
          'Sergeant.',
  'truth': 'Airman Leadership School',
  'decoys': ['The NCO Academy', 'SNCO Academy', 'Chief Leadership Course'],
  'explain': 'Paragraph 7.5 sets ALS as the gate into Staff Sergeant.',
  'source': 'AFH 1 (2025) para 7.5 — ALS Gate.'},
 {'ch': 7,
  'sec': '7B',
  'para': '7.6',
  'title': 'NCO Tier',
  'page': 128,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The 7-skill level is typically earned at the rank of ____.',
  'truth': 'Staff Sergeant',
  'decoys': ['Airman First Class', 'Senior Master Sergeant', 'Airman Basic'],
  'explain': 'Paragraph 7.6 says the 7-skill level is typically earned at Staff Sergeant. The 5-level is '
             'typical at Airman First Class, and the 9-level requires Senior Master Sergeant.',
  'source': 'AFH 1 (2025) para 7.6 — NCO Tier.'},
 {'ch': 7,
  'sec': '7B',
  'para': '7.6',
  'title': 'NCO Tier',
  'page': 128,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The NCO tier is Staff Sergeant and ____.',
  'truth': 'Technical Sergeant',
  'decoys': ['Senior Airman', 'Master Sergeant', 'Chief Master Sergeant'],
  'explain': 'Paragraph 7.6 stops the NCO tier at Technical Sergeant. Master Sergeant opens the SNCO tier.',
  'source': 'AFH 1 (2025) para 7.6 — NCO Tier.'},
 {'ch': 7,
  'sec': '7B',
  'para': '7.7',
  'title': 'SNCOA Gate',
  'page': 128,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? A Master Sergeant must finish the ____ before pinning on '
          'Senior Master Sergeant.',
  'truth': 'SNCO Academy',
  'decoys': ['Airman Leadership School', 'First-term airman center', 'Only a distance CBT'],
  'explain': 'Paragraph 7.7 requires the SNCO Academy before Senior Master Sergeant.',
  'source': 'AFH 1 (2025) para 7.7 — SNCOA Gate.'},
 {'ch': 7,
  'sec': '7F',
  'para': '7.21',
  'title': 'Enlisted PME',
  'page': 140,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Stateside enlisted PME is under AETC at the Thomas N. '
          'Barnes Center, Maxwell AFB-____.',
  'truth': 'Gunter Annex',
  'decoys': ['Lackland', 'Wright-Patterson', 'Hurlburt Field'],
  'explain': 'Paragraph 7.21 places the Barnes Center at Maxwell AFB-Gunter Annex. The other bases host '
             'different missions.',
  'source': 'AFH 1 (2025) para 7.21 — Enlisted PME.'},
 {'ch': 7,
  'sec': '7F',
  'para': '7.21',
  'title': 'Barnes Center',
  'page': 140,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? Stateside enlisted PME schools are run for AETC by the '
          'Barnes Center at ____.',
  'truth': 'Maxwell AFB-Gunter Annex',
  'decoys': ['Lackland only', 'Wright-Patterson', 'MacDill'],
  'explain': 'Paragraph 7.21 places the Barnes Center at Maxwell AFB-Gunter Annex.',
  'source': 'AFH 1 (2025) para 7.21 — Barnes Center.'},
 {'ch': 7,
  'sec': '7G',
  'para': '7.24',
  'title': 'CCAF',
  'page': 144,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? President Ford signed CCAF associate-degree authority on '
          '14 July ____.',
  'truth': '1976',
  'decoys': ['1972', '2004', '1986'],
  'explain': 'Paragraph 7.24 dates Public Law 94-361 to 14 July 1976. The college activated in 1972, '
             'authority moved in 2004, and Goldwater-Nichols is 1986.',
  'source': 'AFH 1 (2025) para 7.24 — CCAF.'},
 {'ch': 7,
  'sec': '7G',
  'para': '7.24',
  'title': 'CCAF',
  'page': 144,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? The Community College of the Air Force was activated in '
          '____.',
  'truth': '1972',
  'decoys': ['1947', '2004', '2016'],
  'explain': 'Paragraph 7.24 dates activation to 1972. 2004 is when degree authority moved to Air '
             'University.',
  'source': 'AFH 1 (2025) para 7.24 — CCAF.'},
 {'ch': 8,
  'sec': '8A',
  'para': '8.3',
  'title': 'ACA Worksheet',
  'page': 152,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The Airman Comprehensive Assessment worksheet for AB '
          'through TSgt is AF Form ____.',
  'truth': '931',
  'decoys': ['932', '724', '988'],
  'explain': 'Paragraph 8.3 assigns AF Form 931 to AB through TSgt. Form 932 is for SNCOs, 724 is for '
             'officers, and 988 is leave.',
  'source': 'AFH 1 (2025) para 8.3 — ACA Worksheet.'},
 {'ch': 8,
  'sec': '8C',
  'para': '8.10',
  'title': 'First-term SRP',
  'page': 158,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? First-term Airmen receive selective reenlistment '
          'consideration within ____ months of ETS.',
  'truth': '15',
  'decoys': ['13', '6', '36'],
  'explain': 'Paragraph 8.10 uses 15 months for first-term Airmen and 13 for the later cohorts named there.',
  'source': 'AFH 1 (2025) para 8.10 — First-term SRP.'},
 {'ch': 8,
  'sec': '8D',
  'para': '8.22',
  'title': 'Decorations',
  'page': 162,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The highest decoration for heroism in military action is '
          'the ____.',
  'truth': 'Medal of Honor',
  'decoys': ['Air Force Cross', 'Silver Star', "Airman's Medal"],
  'explain': 'Paragraph 8.22 calls the Medal of Honor the highest. The Air Force Cross is second, the Silver '
             "Star is third among combat decorations, and the Airman's Medal is for non-combat heroism.",
  'source': 'AFH 1 (2025) para 8.22 — Decorations.'},
 {'ch': 9,
  'sec': '9A',
  'para': '9.2',
  'title': 'Promotion Quotas',
  'page': 171,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? The E-9 strength cap for Regular Air Force is ____ '
          'percent.',
  'truth': '1.25',
  'decoys': ['2.5', '5', '10'],
  'explain': 'Paragraph 9.2 caps E-9 at 1.25 percent and E-8 at 2.5 percent. Five and ten are not those '
             'statutory averages.',
  'source': 'AFH 1 (2025) para 9.2 — Promotion Quotas.'},
 {'ch': 9,
  'sec': '9A',
  'para': '9.2',
  'title': 'E-9 Cap',
  'page': 171,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? The fiscal-year average for E-9 may not exceed ____ '
          'percent of enlisted RegAF strength.',
  'truth': '1.25',
  'decoys': ['2.5', '5', '10'],
  'explain': 'Paragraph 9.2 sets 1.25 percent for E-9 and 2.5 percent for E-8.',
  'source': 'AFH 1 (2025) para 9.2 — E-9 Cap.'},
 {'ch': 9,
  'sec': '9A',
  'para': '9.3',
  'title': 'BTZ Effect',
  'page': 171,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? A below-the-zone Senior Airman stripe is effective ____ '
          'months early.',
  'truth': 'Six',
  'decoys': ['Three', 'Twelve', 'One'],
  'explain': 'Paragraph 9.3 sets the effective date six months before the fully qualified date.',
  'source': 'AFH 1 (2025) para 9.3 — BTZ Effect.'},
 {'ch': 9,
  'sec': '9C',
  'para': '9.11',
  'title': 'Test Compromise',
  'page': 175,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Group study for enlisted promotion testing is ____.',
  'truth': 'strictly prohibited',
  'decoys': ['required for SSgt', 'optional if a chief hosts it', 'encouraged by DAFMAN 36-2664'],
  'explain': 'Paragraph 9.11 and the preface prohibit group study for promotion testing under DAFMAN '
             '36-2664. Requiring or encouraging it contradicts that rule.',
  'source': 'AFH 1 (2025) para 9.11 — Test Compromise.'},
 {'ch': 9,
  'sec': '9D',
  'para': '9.16',
  'title': 'Catalog Date',
  'page': 177,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The enlisted promotions catalog is published each year on '
          '____.',
  'truth': '1 October',
  'decoys': ['15 February', '1 January', '4 July'],
  'explain': 'Paragraph 9.16 says 1 October. 15 February 2025 is the handbook date.',
  'source': 'AFH 1 (2025) para 9.16 — Catalog Date.'},
 {'ch': 9,
  'sec': '9D',
  'para': '9.16',
  'title': 'EPRRC',
  'page': 177,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The Enlisted Promotions References and Requirements '
          'Catalog is published each year on 1 ____.',
  'truth': 'October',
  'decoys': ['January', 'July', 'April'],
  'explain': 'Paragraph 9.16 says the catalog is published annually on 1 October. The other months are not '
             'that release date.',
  'source': 'AFH 1 (2025) para 9.16 — EPRRC.'},
 {'ch': 9,
  'sec': '9D',
  'para': '9.17',
  'title': 'Combined Minimum',
  'page': 177,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? PFE and SKT together must total at least ____ points.',
  'truth': '90',
  'decoys': ['80', '100', '40'],
  'explain': 'Paragraph 9.17 requires a combined 90, with the 40/50 split rule when one score sits on the '
             'floor.',
  'source': 'AFH 1 (2025) para 9.17 — Combined Minimum.'},
 {'ch': 9,
  'sec': '9D',
  'para': '9.17',
  'title': 'PFE Minimum',
  'page': 177,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? The minimum score on a PFE, when an SKT is also taken, is '
          '____ points.',
  'truth': '40',
  'decoys': ['45', '70', '50'],
  'explain': 'Paragraph 9.17 sets 40 as the single-test floor when both tests are taken. 45 is the PFE-only '
             'minimum.',
  'source': 'AFH 1 (2025) para 9.17 — PFE Minimum.'},
 {'ch': 9,
  'sec': '9D',
  'para': '9.17',
  'title': 'Test Scoring',
  'page': 177,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? When both tests are taken, each needs at least 40 and the '
          'combined score must reach ____.',
  'truth': '90',
  'decoys': ['80', '70', '100'],
  'explain': 'Paragraph 9.17 requires a combined 90, with 40 on each test. A 40 and a 40 would total only 80 '
             'and fail.',
  'source': 'AFH 1 (2025) para 9.17 — Test Scoring.'},
 {'ch': 9,
  'sec': '9E',
  'para': '9.19',
  'title': 'Board Panel',
  'page': 179,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? A promotion board panel is one colonel and two ____.',
  'truth': 'Chief master sergeants',
  'decoys': ['Captains', 'Senior airmen', 'Civilians from the booster club'],
  'explain': 'Paragraph 9.19 fixes the panel as one colonel and two chiefs.',
  'source': 'AFH 1 (2025) para 9.19 — Board Panel.'},
 {'ch': 11,
  'sec': '11B',
  'para': '11.12',
  'title': 'Leave Management',
  'page': 215,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? If LeaveWeb is down, leave may be requested on DAF Form '
          '____.',
  'truth': '988',
  'decoys': ['931', '702', '357'],
  'explain': 'Paragraph 11.12 names DAF Form 988 as the fallback leave form. Form 931 is feedback, 702 is '
             'the LES, and 357 is family care.',
  'source': 'AFH 1 (2025) para 11.12 — Leave Management.'},
 {'ch': 11,
  'sec': '11B',
  'para': '11.12',
  'title': 'Leave Form',
  'page': 215,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? When LeaveWeb is down, the fallback leave form is DAF Form '
          '____.',
  'truth': '988',
  'decoys': ['910', '847', '702'],
  'explain': 'Paragraph 11.12 names DAF Form 988. DFAS Form 702 is the LES.',
  'source': 'AFH 1 (2025) para 11.12 — Leave Form.'},
 {'ch': 11,
  'sec': '11B',
  'para': '11.14',
  'title': 'Accruing Leave',
  'page': 215,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? Members accrue ____ days of leave for each month of '
          'Regular Air Force status.',
  'truth': '2.5',
  'decoys': ['3.0', '1.5', '5.0'],
  'explain': 'Paragraph 11.14 sets accrual at 2.5 days per month. The other rates are not the accrual rule.',
  'source': 'AFH 1 (2025) para 11.14 — Accruing Leave.'},
 {'ch': 11,
  'sec': '11B',
  'para': '11.14',
  'title': 'Leave Cap',
  'page': 215,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Ordinary leave carryover into the next fiscal year is '
          'capped at ____ days.',
  'truth': '60',
  'decoys': ['30', '75', '90'],
  'explain': 'Paragraph 11.14 sets 60 days unless a higher balance is specifically authorized.',
  'source': 'AFH 1 (2025) para 11.14 — Leave Cap.'},
 {'ch': 11,
  'sec': '11B',
  'para': '11.14',
  'title': 'Leave Accrual',
  'page': 215,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? RegAF members accrue ____ days of leave each month.',
  'truth': '2.5',
  'decoys': ['2', '5', '1.5'],
  'explain': 'Paragraph 11.14 states 2.5 days per month.',
  'source': 'AFH 1 (2025) para 11.14 — Leave Accrual.'},
 {'ch': 11,
  'sec': '11B',
  'para': '11.14',
  'title': 'Accruing Leave',
  'page': 215,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Unless specifically authorized, the most leave that may be '
          'carried into a new fiscal year is ____ days.',
  'truth': '60',
  'decoys': ['30', '90', '75'],
  'explain': 'Paragraph 11.14 sets the normal carryover maximum at 60 days. Thirty, 75, and 90 are not that '
             'cap.',
  'source': 'AFH 1 (2025) para 11.14 — Accruing Leave.'},
 {'ch': 12,
  'sec': '12A',
  'para': '12.3',
  'title': 'LES',
  'page': 225,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The military Leave and Earnings Statement is DFAS Form '
          '____.',
  'truth': '702',
  'decoys': ['988', '910', '1206'],
  'explain': 'Paragraph 12.3 identifies DFAS Form 702.',
  'source': 'AFH 1 (2025) para 12.3 — LES.'},
 {'ch': 12,
  'sec': '12B',
  'para': '12.19',
  'title': 'GTCC',
  'page': 231,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? ATM advances on the travel card will not be taken earlier '
          'than ____ working days before travel.',
  'truth': 'three',
  'decoys': ['ten', 'thirty', 'zero'],
  'explain': 'Paragraph 12.19 bars ATM advances earlier than three working days before scheduled travel. '
             'Ten, thirty, and same-day-unlimited are not the rule.',
  'source': 'AFH 1 (2025) para 12.19 — GTCC.'},
 {'ch': 12,
  'sec': '12B',
  'para': '12.19',
  'title': 'Travel Card Timing',
  'page': 231,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? GTCC cash advances should not be taken earlier than ____ '
          'working days before travel.',
  'truth': 'Three',
  'decoys': ['Ten', 'One', 'Fourteen'],
  'explain': 'Paragraph 12.19 sets three working days.',
  'source': 'AFH 1 (2025) para 12.19 — Travel Card Timing.'},
 {'ch': 12,
  'sec': '12D',
  'para': '12.27',
  'title': 'Fiscal Year',
  'page': 238,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The Air Force fiscal year begins on ____.',
  'truth': '1 October',
  'decoys': ['1 January', '1 July', '15 February'],
  'explain': 'The resources section runs the fiscal year from 1 October through 30 September.',
  'source': 'AFH 1 (2025) para 12.27 — Fiscal Year.'},
 {'ch': 12,
  'sec': '12D',
  'para': '12.27',
  'title': 'Fiscal Year',
  'page': 238,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The fiscal year runs from 1 October through 30 ____.',
  'truth': 'September',
  'decoys': ['June', 'December', 'March'],
  'explain': 'Paragraph 12.27 sets the fiscal year as 1 October through 30 September. The other months end '
             'different calendars.',
  'source': 'AFH 1 (2025) para 12.27 — Fiscal Year.'},
 {'ch': 12,
  'sec': '12D',
  'para': '12.28',
  'title': 'POM',
  'page': 238,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? Programming in PPBE produces the Program ____ Memorandum.',
  'truth': 'Objective',
  'decoys': ['Operations', 'Budget', 'Execution'],
  'explain': 'Paragraph 12.28 names the Program Objective Memorandum as the programming product.',
  'source': 'AFH 1 (2025) para 12.28 — POM.'},
 {'ch': 12,
  'sec': '12D',
  'para': '12.28',
  'title': 'PPBE',
  'page': 238,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The programming phase produces the Program Objective ____.',
  'truth': 'Memorandum',
  'decoys': ['Budget', 'Catalog', 'Assessment'],
  'explain': "Paragraph 12.28 says programming's key product is the Program Objective Memorandum. Budget, "
             'catalog, and assessment are other products.',
  'source': 'AFH 1 (2025) para 12.28 — PPBE.'},
 {'ch': 13,
  'sec': '13C',
  'para': '13.11',
  'title': 'Lewin',
  'page': 252,
  'ranks': 'e6',
  'diff': 2,
  'stem': "Which completion is the handbook line? Lewin's three stages are unfreezing, changing, and ____.",
  'truth': 'Refreezing',
  'decoys': ['Rebriefing', 'Reassigning', 'Retiring'],
  'explain': 'Paragraph 13.11 ends the model with refreezing so the new behavior sticks.',
  'source': 'AFH 1 (2025) para 13.11 — Lewin.'},
 {'ch': 13,
  'sec': '13C',
  'para': '13.12',
  'title': 'Lean',
  'page': 252,
  'ranks': 'e6',
  'diff': 3,
  'stem': 'Which completion is the handbook line? Lean is the continuous-improvement method aimed at '
          'workflow and ____.',
  'truth': 'Eliminating non-value-added waste',
  'decoys': ['Statistical variation only', 'A single bottleneck only', 'Rewriting the oath'],
  'explain': 'Paragraph 13.12 assigns waste and flow to Lean. Variation is Six Sigma.',
  'source': 'AFH 1 (2025) para 13.12 — Lean.'},
 {'ch': 13,
  'sec': '13C',
  'para': '13.12',
  'title': 'Continuous Improvement',
  'page': 252,
  'ranks': 'e6',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Six Sigma focuses on reducing process ____.',
  'truth': 'variation',
  'decoys': ['non-value-added waste only', 'bottlenecks only', 'promotion quotas'],
  'explain': "Paragraph 13.12 assigns variation to Six Sigma. Waste is Lean's focus, bottlenecks are Theory "
             'of Constraints, and quotas are a promotion topic.',
  'source': 'AFH 1 (2025) para 13.12 — Continuous Improvement.'},
 {'ch': 13,
  'sec': '13C',
  'para': '13.13',
  'title': 'PPSM Steps',
  'page': 252,
  'ranks': 'e6',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The practical problem-solving method has ____ steps.',
  'truth': 'Eight',
  'decoys': ['Five', 'Three', 'Twelve'],
  'explain': 'Paragraph 13.13 describes eight steps. Five is risk management and three is Lewin.',
  'source': 'AFH 1 (2025) para 13.13 — PPSM Steps.'},
 {'ch': 14,
  'sec': '14A',
  'para': '14.2',
  'title': 'Stages of Team Building',
  'page': 260,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? Teams move through forming, storming, norming, and ____.',
  'truth': 'performing',
  'decoys': ['refreezing', 'adjourning as a required fifth Air Force stage', 'coercing'],
  'explain': 'Paragraph 14.2 ends the four stages with performing. Refreezing and coercion are change ideas, '
             "and the handbook's list stops at performing.",
  'source': 'AFH 1 (2025) para 14.2 — Stages of Team Building.'},
 {'ch': 14,
  'sec': '14A',
  'para': '14.2',
  'title': 'Team Stages',
  'page': 260,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The four team stages are forming, storming, norming, and '
          '____.',
  'truth': 'Performing',
  'decoys': ['Punishing', 'Promoting', 'Parking'],
  'explain': 'Paragraph 14.2 ends with performing, when the team can actually solve problems.',
  'source': 'AFH 1 (2025) para 14.2 — Team Stages.'},
 {'ch': 14,
  'sec': '14D',
  'para': '14.24',
  'title': 'Full Range Leadership',
  'page': 271,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Full Range Leadership Development has three elements: '
          'leader, follower, and ____.',
  'truth': 'situation',
  'decoys': ['senior rater', 'budget', 'installation'],
  'explain': 'Paragraph 14.24 names the situation as the third element. Senior rater, budget, and '
             'installation are not that trio.',
  'source': 'AFH 1 (2025) para 14.24 — Full Range Leadership.'},
 {'ch': 14,
  'sec': '14D',
  'para': '14.24',
  'title': 'FRLD Elements',
  'page': 271,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Full-range leadership is the leader, the follower, and the '
          '____.',
  'truth': 'Situation',
  'decoys': ['Budget', 'Aircraft', 'Slogan'],
  'explain': 'Paragraph 14.24 names the situation as the third element.',
  'source': 'AFH 1 (2025) para 14.24 — FRLD Elements.'},
 {'ch': 14,
  'sec': '14D',
  'para': '14.25',
  'title': 'Transformational I',
  'page': 271,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? One transformational component is idealized ____.',
  'truth': 'Influence',
  'decoys': ['Indifference', 'Inventory', 'Isolation'],
  'explain': 'Paragraph 14.25 lists idealized influence among the four transformational components.',
  'source': 'AFH 1 (2025) para 14.25 — Transformational I.'},
 {'ch': 14,
  'sec': '14D',
  'para': '14.25',
  'title': 'FRLD Model',
  'page': 271,
  'ranks': 'both',
  'diff': 2,
  'stem': "Which completion is the handbook line? The four transformational I's include idealized influence "
          'and inspirational ____.',
  'truth': 'motivation',
  'decoys': ['inspection', 'inventory', 'isolation'],
  'explain': "Paragraph 14.25 names inspirational motivation as one of the four I's. Inspection, inventory, "
             'and isolation are not those components.',
  'source': 'AFH 1 (2025) para 14.25 — FRLD Model.'},
 {'ch': 15,
  'sec': '15A',
  'para': '15.1',
  'title': 'Accountability',
  'page': 279,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? Accountability includes reliability, honesty, and '
          'responsibility for self and ____.',
  'truth': 'The team',
  'decoys': ['The rumor', "Yesterday's shift only", 'Nobody else'],
  'explain': 'Paragraph 15.1 explicitly includes the team, not only private conduct.',
  'source': 'AFH 1 (2025) para 15.1 — Accountability.'},
 {'ch': 15,
  'sec': '15A',
  'para': '15.1',
  'title': 'Accountability',
  'page': 279,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Surveys rate ____ as the most important foundational '
          'competency.',
  'truth': 'accountability',
  'decoys': ['charisma', 'drill precision', 'digital literacy'],
  'explain': 'Paragraph 15.1 says surveys consistently rate accountability as the most important '
             'foundational competency. The other traits are not the one named.',
  'source': 'AFH 1 (2025) para 15.1 — Accountability.'},
 {'ch': 15,
  'sec': '15A',
  'para': '15.2',
  'title': 'Perseverance',
  'page': 279,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? A ____ mindset treats ability as something you can '
          'improve.',
  'truth': 'growth',
  'decoys': ['fixed', 'laissez-faire', 'mechanistic'],
  'explain': 'Paragraph 15.2 defines the growth mindset as belief in the capacity to improve. Fixed mindset '
             'treats qualities as permanent. The other words are leadership and structure terms.',
  'source': 'AFH 1 (2025) para 15.2 — Perseverance.'},
 {'ch': 15,
  'sec': '15A',
  'para': '15.2',
  'title': 'Growth Mindset',
  'page': 279,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? A growth mindset treats ability as something that can '
          '____.',
  'truth': 'Change with effort',
  'decoys': ['Never move', 'Be inherited only', 'Be hidden'],
  'explain': 'Paragraph 15.2 defines growth mindset as belief in real change through effort.',
  'source': 'AFH 1 (2025) para 15.2 — Growth Mindset.'},
 {'ch': 15,
  'sec': '15C',
  'para': '15.14',
  'title': 'FOCUS',
  'page': 288,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? FOCUS communication is focused, organized, clear, '
          'understanding, and ____.',
  'truth': 'supported',
  'decoys': ['secret', 'sudden', 'silent'],
  'explain': 'Paragraph 15.14 ends FOCUS with supported. Secret, sudden, and silent are not the fifth '
             'principle.',
  'source': 'AFH 1 (2025) para 15.14 — FOCUS.'},
 {'ch': 15,
  'sec': '15C',
  'para': '15.15',
  'title': 'Seven Steps',
  'page': 288,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? Step 7 of effective communication is to fight for feedback '
          'and get ____.',
  'truth': 'approval',
  'decoys': ['a clearance', 'a decoration', 'a sequence number'],
  'explain': 'Paragraph 15.15 names step 7 as fight for feedback and get approval. Clearance, decoration, '
             'and sequence number are other processes.',
  'source': 'AFH 1 (2025) para 15.15 — Seven Steps.'},
 {'ch': 16,
  'sec': '16A',
  'para': '16A',
  'title': 'What We Know',
  'page': 304,
  'ranks': 'e6',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The Developing Ideas chapter starts by separating what the '
          'team knows from ____.',
  'truth': 'What it still has to find out',
  'decoys': ['Who outranks the room', 'Which slogan tests well', 'How fast the brief can end'],
  'explain': 'Section 16A frames idea work as knowing the difference between settled facts and open '
             'questions.',
  'source': 'AFH 1 (2025) para 16A — What We Know.'},
 {'ch': 16,
  'sec': '16B',
  'para': '16B',
  'title': 'Cognitive Processes',
  'page': 306,
  'ranks': 'e6',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Divergent thinking in the Developing Ideas chapter is for '
          '____ before the team narrows.',
  'truth': 'Opening the field of options',
  'decoys': ['Signing the final slide', 'Picking the first familiar fix', 'Skipping the data'],
  'explain': 'Section 16B treats divergent thinking as the wide pass. Convergent thinking is the later '
             'narrowing.',
  'source': 'AFH 1 (2025) para 16B — Cognitive Processes.'},
 {'ch': 16,
  'sec': '16C',
  'para': '16C',
  'title': 'Informed Decision-Making',
  'page': 313,
  'ranks': 'e6',
  'diff': 3,
  'stem': 'Which completion is the handbook line? An informed decision waits when the problem is still ____.',
  'truth': 'Not validated',
  'decoys': ['Already solved by a purchase', 'Too dull for a meeting', 'Owned by the loudest voice'],
  'explain': 'Section 16C says an informed decision needs a validated problem, not a solution assumed in the '
             'first sentence.',
  'source': 'AFH 1 (2025) para 16C — Informed Decision-Making.'},
 {'ch': 17,
  'sec': '17F',
  'para': '17F',
  'title': 'Risk Steps',
  'page': 336,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Risk management ends by supervising and ____ the controls.',
  'truth': 'Evaluating',
  'decoys': ['Ignoring', 'Deleting', 'Celebrating'],
  'explain': 'Section 17F closes the cycle with supervise and evaluate.',
  'source': 'AFH 1 (2025) para 17F — Risk Steps.'},
 {'ch': 17,
  'sec': '17F',
  'para': '17F',
  'title': 'Risk Management',
  'page': 336,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The last risk-management step is supervise and ____.',
  'truth': 'evaluate',
  'decoys': ['classify', 'promote', 'salute'],
  'explain': 'The cycle ends with supervise and evaluate. Classify, promote, and salute are not that step.',
  'source': 'AFH 1 (2025) para 17F — Risk Management.'},
 {'ch': 18,
  'sec': '18B',
  'para': '18B',
  'title': 'Operations Security',
  'page': 346,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? OPSEC starts by identifying ____ information.',
  'truth': 'critical',
  'decoys': ['all public', 'personal social', 'already published'],
  'explain': 'The first OPSEC step is to identify critical information. Public, personal, and already '
             'published material is not the starting category.',
  'source': 'AFH 1 (2025) para 18B — Operations Security.'},
 {'ch': 18,
  'sec': '18B',
  'para': '18B',
  'title': 'OPSEC First Step',
  'page': 346,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The OPSEC process starts by identifying ____ information.',
  'truth': 'Critical',
  'decoys': ['Comforting', 'Classified only', 'Public affairs only'],
  'explain': 'Section 18B starts with critical information, which can be unclassified.',
  'source': 'AFH 1 (2025) para 18B — OPSEC First Step.'},
 {'ch': 18,
  'sec': '18E',
  'para': '18E',
  'title': 'Antiterrorism',
  'page': 357,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? FPCON from lowest to highest is Normal, Alpha, Bravo, '
          'Charlie, and ____.',
  'truth': 'Delta',
  'decoys': ['Echo', 'Foxtrot', 'Zulu'],
  'explain': 'The scale ends at Delta. Echo, Foxtrot, and Zulu are phonetic letters, not a higher FPCON.',
  'source': 'AFH 1 (2025) para 18E — Antiterrorism.'},
 {'ch': 18,
  'sec': '18E',
  'para': '18E',
  'title': 'FPCON Top',
  'page': 357,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The highest force-protection condition in the Air Force '
          'scale is ____.',
  'truth': 'Delta',
  'decoys': ['Normal', 'Alpha', 'Bravo'],
  'explain': 'Section 18E places Delta at the top, for an imminent or actual attack.',
  'source': 'AFH 1 (2025) para 18E — FPCON Top.'},
 {'ch': 19,
  'sec': '19B',
  'para': '19B',
  'title': 'Law of War Count',
  'page': 365,
  'ranks': 'both',
  'diff': 3,
  'stem': 'Which completion is the handbook line? One law-of-war principle that limits civilian harm against '
          'military gain is ____.',
  'truth': 'Proportionality',
  'decoys': ['Popularity', 'Punctuality', 'Promotion'],
  'explain': 'Section 19B includes proportionality among the law-of-war principles.',
  'source': 'AFH 1 (2025) para 19B — Law of War Count.'},
 {'ch': 19,
  'sec': '19B',
  'para': '19B',
  'title': 'Law of War',
  'page': 365,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The law-of-war principles include military necessity, '
          'humanity, distinction, proportionality, and ____.',
  'truth': 'honor',
  'decoys': ['haste', 'secrecy', 'surprise'],
  'explain': 'Honor is the fifth principle. Haste, secrecy, and surprise are not that list.',
  'source': 'AFH 1 (2025) para 19B — Law of War.'},
 {'ch': 19,
  'sec': '19C',
  'para': '19C',
  'title': 'Code of Conduct',
  'page': 371,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? Article V requires name, rank, service number, and date of '
          '____.',
  'truth': 'birth',
  'decoys': ['commission', 'last deployment', 'security clearance'],
  'explain': 'Article V lists date of birth with name, rank, and service number. Commission date, '
             'deployments, and clearance data are not the article.',
  'source': 'AFH 1 (2025) para 19C — Code of Conduct.'},
 {'ch': 19,
  'sec': '19C',
  'para': '19C',
  'title': 'Code Article V',
  'page': 371,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Under Code of Conduct Article V, a prisoner gives name, '
          'rank, service number, and ____.',
  'truth': 'Date of birth',
  'decoys': ['Home address', 'Unit mission', "Next of kin's workplace"],
  'explain': 'Article V limits the required identification to name, rank, service number, and date of birth.',
  'source': 'AFH 1 (2025) para 19C — Code Article V.'},
 {'ch': 20,
  'sec': '20C',
  'para': '20C',
  'title': 'Unprofessional Relationships',
  'page': 385,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? An unprofessional relationship compromises, or appears to '
          'compromise, ____.',
  'truth': 'Good order or the chain of command',
  'decoys': ['Lunch plans only', 'Nothing if both agree', 'Only social media metrics'],
  'explain': 'Section 20C keys on good order and the chain, including the appearance of favoritism.',
  'source': 'AFH 1 (2025) para 20C — Unprofessional Relationships.'},
 {'ch': 22,
  'sec': '22A',
  'para': '22A',
  'title': 'USAF Fitness',
  'page': 414,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? The purpose of fitness is a force that is ____ for the '
          'mission.',
  'truth': 'ready',
  'decoys': ['decorated', 'exempt', 'unmeasured'],
  'explain': 'Fitness exists to keep Airmen ready. Decorations, exemptions, and refusing to measure '
             'readiness are not the purpose.',
  'source': 'AFH 1 (2025) para 22A — USAF Fitness.'},
 {'ch': 22,
  'sec': '22D',
  'para': '22D',
  'title': 'Readiness and Substances',
  'page': 429,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Illegal drug use is treated as incompatible with service '
          'because it breaks ____.',
  'truth': 'Readiness and trust',
  'decoys': ['Only the dress manual', 'Nothing if undetected', 'The fiscal year'],
  'explain': 'Section 22D connects substance abuse to a ready, trustworthy force.',
  'source': 'AFH 1 (2025) para 22D — Readiness and Substances.'},
 {'ch': 24,
  'sec': '24A',
  'para': '24A',
  'title': 'Traditions',
  'page': 543,
  'ranks': 'both',
  'diff': 2,
  'stem': 'Which completion is the handbook line? Military customs exist to pass down standards and ____.',
  'truth': 'Heritage',
  'decoys': ['Rumors', 'Shortcuts', 'Nicknames only'],
  'explain': 'Chapter 24 ties customs to heritage and respect, not to unofficial shortcuts.',
  'source': 'AFH 1 (2025) para 24A — Traditions.'},
 {'ch': 24,
  'sec': '24B',
  'para': '24B',
  'title': 'Respect for the Flag',
  'page': 547,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? The United States flag is never ____.',
  'truth': 'dipped',
  'decoys': ['raised at reveille', 'lowered at retreat', 'displayed with the union in the honor position'],
  'explain': 'The flag is never dipped. Raising it at reveille, lowering it at retreat, and keeping the '
             'union in the honor position are correct courtesies.',
  'source': 'AFH 1 (2025) para 24B — Respect for the Flag.'},
 {'ch': 24,
  'sec': '24D',
  'para': '24D',
  'title': 'Ceremonies and Events',
  'page': 557,
  'ranks': 'both',
  'diff': 1,
  'stem': 'Which completion is the handbook line? Reveille ____ the flag, and retreat lowers it.',
  'truth': 'raises',
  'decoys': ['folds', 'dips', 'retires from service'],
  'explain': 'Reveille raises the flag at the start of the day. Folding, dipping, and retirement are not '
             'that ceremony.',
  'source': 'AFH 1 (2025) para 24D — Ceremonies and Events.'}]
