"""MCQ fills for WAPS sections that had fewer than three items.

Original wording. Facts are the public AFH 1 (15 February 2025) points
already used in this bank. explain is study copy. source is the locator.
"""

MCQ_THIN = [
    {
        "ch": 7, "sec": "7D", "para": "7.10", "title": "Force Development",
        "page": 133, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Which catalog does the handbook place inside the force-development web tool?",
        "correct": "A developmental-experience catalog",
        "w1": "The WAPS study catalog",
        "w2": "The decorations catalog",
        "w3": "The chargeable-leave catalog",
        "explain": "The force-development tool is where Airmen look up developmental experiences along with mentoring. The WAPS catalog, decorations, and leave live in other systems.",
        "source": "AFH 1 (2025) para 7.10 — Force Development.",
    },
    {
        "ch": 7, "sec": "7D", "para": "7.10", "title": "Force Development",
        "page": 133, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Mentoring inside the force-development tool is meant to do what?",
        "correct": "Connect Airmen with mentors as part of deliberate development",
        "w1": "Replace the rating chain on the evaluation",
        "w2": "Score the promotion fitness examination",
        "w3": "Authorize chargeable leave",
        "explain": "Mentoring in this tool supports development. It does not replace the rater, score a promotion test, or approve leave.",
        "source": "AFH 1 (2025) para 7.10 — Force Development.",
    },
    {
        "ch": 7, "sec": "7H", "para": "7.26", "title": "Continuing Education",
        "page": 148, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Military Tuition Assistance, in the continuing-education section, pays toward what kind of study?",
        "correct": "Voluntary off-duty education",
        "w1": "A mandatory PME school seat",
        "w2": "A decoration entitlement",
        "w3": "A fitness-assessment exemption",
        "explain": "Tuition Assistance helps pay for off-duty courses. PME seats, decorations, and fitness exemptions are different programs.",
        "source": "AFH 1 (2025) para 7.26 — Continuing Education.",
    },
    {
        "ch": 7, "sec": "7H", "para": "7.26", "title": "Continuing Education",
        "page": 148, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Why does the Post-9/11 GI Bill appear in the continuing-education section?",
        "correct": "It helps pay for education after qualifying service",
        "w1": "It replaces monthly basic pay",
        "w2": "It sets the E-9 strength cap",
        "w3": "It funds only in-residence PME",
        "explain": "It is an education benefit tied to service. It is not a pay table, a promotion quota, or a PME school seat.",
        "source": "AFH 1 (2025) para 7.26 — Continuing Education.",
    },
    {
        "ch": 11, "sec": "11C", "para": "11.18", "title": "Military Associations",
        "page": 219, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Why does the handbook say a private association is not a promotion requirement?",
        "correct": "Membership is voluntary and sits outside the rating chain",
        "w1": "Associations write the promotion fitness examination",
        "w2": "Associations assign official duty titles",
        "w3": "Associations control chargeable leave",
        "explain": "Private associations can support Airmen, but they do not sit in the chain of command and they are not a condition of promotion.",
        "source": "AFH 1 (2025) para 11.18 — Military Associations.",
    },
    {
        "ch": 11, "sec": "11D", "para": "11.26", "title": "Civilian Pay",
        "page": 220, "ranks": "both", "diff": 3, "tags": "waps",
        "question": "How does the handbook contrast Federal Wage System pay with General Schedule pay?",
        "correct": "Federal Wage System pay is an hourly wage with five steps",
        "w1": "Federal Wage System pay is an annual salary with ten steps",
        "w2": "Federal Wage System pay is a one-time bonus",
        "w3": "Federal Wage System pay is counted in leave days",
        "explain": "General Schedule pay in this section is an annual salary with ten steps. The Federal Wage System is the hourly scale with five steps. Bonuses and leave are not that pay scale.",
        "source": "AFH 1 (2025) para 11.26 — Civilian Pay.",
    },
    {
        "ch": 12, "sec": "12E", "para": "12.34", "title": "Environmental Management",
        "page": 244, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Continuous improvement, as an environmental-management priority, asks the unit to do what?",
        "correct": "Keep tightening how it meets environmental duties while doing the mission",
        "w1": "Skip compliance whenever the mission calendar is full",
        "w2": "Treat the environment section as optional reading",
        "w3": "Replace the fiscal year with a new calendar",
        "explain": "Continuous improvement sits with compliance and risk reduction. It does not cancel the mission, and it does not rewrite the budget calendar.",
        "source": "AFH 1 (2025) para 12.34 — Environmental Management.",
    },
    {
        "ch": 15, "sec": "15D", "para": "15.22", "title": "Staff Work",
        "page": 293, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "What should a decision-maker be able to see in a finished staff package?",
        "correct": "The recommendation, the facts behind it, and the decision being asked",
        "w1": "Only the author's mood",
        "w2": "A social-media draft and nothing else",
        "w3": "A request that the package itself outrank the commander",
        "explain": "A staff package organizes the decision so the reader can see the ask and the facts. It does not hide the recommendation, and it does not take the decision away from the person authorized to make it.",
        "source": "AFH 1 (2025) para 15.22 — Staff Work.",
    },
    {
        "ch": 15, "sec": "15E", "para": "15.31", "title": "Effective Listening",
        "page": 295, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Effective listening, in the spoken-communication section, starts with what?",
        "correct": "Paying attention to the speaker instead of planning your reply",
        "w1": "Interrupting to display rank",
        "w2": "Waiting only for a mistake to quote later",
        "w3": "Recording the talk for a social-media post",
        "explain": "Listening is how a leader collects information the team already has. Rank display, gotcha quotes, and a recording for an audience are not the skill.",
        "source": "AFH 1 (2025) para 15.31 — Effective Listening.",
    },
    {
        "ch": 15, "sec": "15F", "para": "15.33", "title": "Government Systems",
        "page": 300, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Limited personal use of a government communication system fails the handbook test when it does what?",
        "correct": "Interferes with duty or discredits the service",
        "w1": "Stays short, rare, and approved",
        "w2": "Uses official email for an official task",
        "w3": "Follows the local rule on reasonable use",
        "explain": "The allowance is narrow: reasonable, approved, and harmless to duty and the service. Interference or discredit ends the allowance.",
        "source": "AFH 1 (2025) para 15.33 — Government Systems.",
    },
    {
        "ch": 16, "sec": "16A", "para": "16A", "title": "What We Know",
        "page": 304, "ranks": "e6", "diff": 2, "tags": "waps,e6",
        "question": "Before a team treats a claim as known, the What We Know section expects them to ask what?",
        "correct": "What evidence supports it",
        "w1": "Who spoke the loudest",
        "w2": "Which answer ends the meeting fastest",
        "w3": "Whether the claim flatters the unit",
        "explain": "What the team knows means facts it can support. Volume, speed, and flattery do not turn an assumption into knowledge.",
        "source": "AFH 1 (2025) section 16A — What We Know.",
    },
    {
        "ch": 16, "sec": "16A", "para": "16A", "title": "What We Know",
        "page": 304, "ranks": "e6", "diff": 2, "tags": "waps,e6",
        "question": "Where does an unchecked assumption belong in this chapter's frame?",
        "correct": "Outside what the team knows, until someone checks it",
        "w1": "Inside the known pile if a senior said it",
        "w2": "In the decorations chapter",
        "w3": "On the leave form as a fact",
        "explain": "Rank does not convert an assumption into a checked fact. The section wants those piles kept apart.",
        "source": "AFH 1 (2025) section 16A — What We Know.",
    },
    {
        "ch": 17, "sec": "17B", "para": "17B", "title": "Disasters, Attacks, and Hazards",
        "page": 323, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Which threat picture includes a hostile chemical, biological, radiological, or nuclear attack?",
        "correct": "The disasters, attacks, and hazards section of emergency management",
        "w1": "The dress and appearance chapter",
        "w2": "The leave-management section",
        "w3": "The promotion-testing section",
        "explain": "CBRN attacks are part of the hazard picture with natural disasters and major accidents. Uniforms, leave, and testing are covered elsewhere.",
        "source": "AFH 1 (2025) section 17B — Disasters, Attacks, and Hazards.",
    },
    {
        "ch": 18, "sec": "18D", "para": "18D", "title": "Cyber Security and Mobility",
        "page": 353, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Sharing a network password so a teammate can check email violates which idea in the cyber section?",
        "correct": "An account is access to government information, not a favor to lend",
        "w1": "Any personal device is automatically approved for mobility",
        "w2": "Operations security covers paper records only",
        "w3": "FPCON Delta is the form used to share passwords",
        "explain": "Credentials are keys. Lending them bypasses the control that ties access to a person. Device approval, paper-only operations security, and force-protection conditions are different controls.",
        "source": "AFH 1 (2025) section 18D — Information Access, Cyber Security, and Mobility.",
    },
    {
        "ch": 24, "sec": "24F", "para": "24F", "title": "Preserving Our Heritage",
        "page": 564, "ranks": "both", "diff": 2, "tags": "waps",
        "question": "Passing heritage forward fails when the story is what?",
        "correct": "Rewritten so it sounds better than the record",
        "w1": "Tied to a real standard Airmen still keep",
        "w2": "Told accurately to new Airmen",
        "w3": "Used to explain why a custom exists",
        "explain": "The section asks for an accurate handoff. Polishing a story until it is false does not preserve heritage.",
        "source": "AFH 1 (2025) section 24F — Preserving Our Heritage.",
    },
]
