/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0a19d5233f1faa840df60faf6ce6f6d3)
interface __BaseEnv_Env {
	JOIN_LIMIT: RateLimit;
	ALLOWED_ORIGINS: "https://pdg-play.com,https://www.pdg-play.com";
	PARTY_ROOM: DurableObjectNamespace<import("./src/index").PartyRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PartyRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
